missing_charge: Avoid creating Stripe charges without billing log entries or central routing.
missing_refund: Avoid issuing refunds without corresponding ledger entries.
missing_failure_log: Avoid handling Stripe failures without logging the event.
unapproved_workflow: Avoid running Stripe workflows without explicit approval.
unknown_webhook: Avoid unregistered Stripe webhooks; register endpoints before use.
disabled_webhook: Avoid relying on disabled Stripe webhook endpoints.
revenue_mismatch: Avoid revenue figures that diverge from ledger or ROI projections.
account_mismatch: Avoid routing charges to unexpected Stripe accounts.
