paths:
  data_dir: /srv/igi/data
  log_dir: /srv/igi/logs
logging:
  verbosity: WARNING
thresholds:
  alert: 0.95
bot:
  learning_rate: 0.005
api_keys:
  openai: prod-openai-key
  serp: prod-serp-key
# Dedicated Stack retrieval paths for production deployments
context_builder:
  stack:
    index_path: /srv/igi/data/stack/index.faiss
    metadata_path: /srv/igi/data/stack/metadata.db
    cache_dir: /srv/igi/data/stack/cache
    progress_path: /srv/igi/data/stack/cache/progress.sqlite
# Ranker scheduler environment variables:
# - RANKER_SCHEDULER_INTERVAL: seconds between retrains (0 disables)
# - RANKER_SCHEDULER_ROI_THRESHOLD: ROI delta triggering immediate retrain
# - RANKER_SCHEDULER_RISK_THRESHOLD: risk delta triggering immediate retrain
# - RANKER_SCHEDULER_EVENT_LOG: path to SQLite log for UnifiedEventBus
# - RANKER_SCHEDULER_RABBITMQ_HOST: RabbitMQ host for event mirroring
