# Configuration defaults for Stack dataset ingestion and retrieval.
#
# These values are merged into the main configuration by ``config.load_config``
# and can be overridden per-environment by editing this file. ``enabled`` acts
# as a global kill-switch so deployments without Stack embeddings can skip
# ingestion and retrieval logic entirely.
stack_dataset:
  enabled: false
  languages:
    - python
    - javascript
  max_lines: 800
  max_bytes: 262144
  retrieval_top_k: 5
  index_path: stack/index.faiss
  metadata_path: stack/metadata.db
  cache_dir: stack/cache
  progress_path: stack/cache/progress.sqlite
  chunk_lines: 512

# Context builder specific tuning for Stack retrieval. These settings control
# whether Stack snippets are considered alongside the primary databases and how
# the snippets are summarised before being merged into prompts.
context_builder:
  # Toggle Stack retrieval without touching ingestion. Disable when the Stack
  # embeddings are unavailable in the current deployment.
  stack:
    enabled: false
    languages:
      - python
      - javascript
    max_lines: 200
    max_bytes: 65536
    retrieval_top_k: 3
    index_path: stack/index.faiss
    metadata_path: stack/metadata.db
    cache_dir: stack/cache
    progress_path: stack/cache/progress.sqlite
    chunk_lines: 256

  stack_prompt_enabled: false
  stack_prompt_limit: 2
