# Routing rules for ``stripe_billing_router``. Each route includes an
# ``account_id`` indicating which Stripe account should receive the charge.
# If omitted, the master account is assumed.  All actions are logged via the
# billing log database.
allowed_secret_keys:
  - sk_live_dummy
stripe:
  default:
    finance:
      finance_router_bot:
        product_id: prod_finance_router
        price_id: price_finance_standard
        customer_id: cus_finance_default
        account_id: acct_master
        currency: usd
  eu:
    finance:
      finance_router_bot:
        product_id: prod_finance_router_eu
        price_id: price_finance_eu
        customer_id: cus_finance_eu
        account_id: acct_master
        currency: eur
