stripe:
  default:
    finance:
      finance_router_bot:
        product_id: prod_finance_router
        price_id: price_finance_standard
        customer_id: cus_finance_default
        currency: usd
  eu:
    finance:
      finance_router_bot:
        product_id: prod_finance_router_eu
        price_id: price_finance_eu
        customer_id: cus_finance_eu
        currency: eur
