version: '3.8'
services:
  api:
    build: ..
    env_file:
      - ../.env
    environment:
      NEURO_BACKUP_INTERVAL: ${NEURO_BACKUP_INTERVAL:-3600}
      NEURO_BACKUP_PATH: ${NEURO_BACKUP_PATH:-/backups/backup.json}
      # explicitly set defaults override .env values
      NEURO_DB_URL: ${NEURO_DB_URL:-postgresql://neuro:neuro@db/neuro}
      NEURO_DB_POOL_SIZE: ${NEURO_DB_POOL_SIZE:-5}
      NEURO_DB_MAX_OVERFLOW: ${NEURO_DB_MAX_OVERFLOW:-10}
    ports:
      - "8000:8000"
    volumes:
      - ./backups:/backups
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: neuro
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: neuro
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
