profitability: "optimise revenue streams; reduce costs"
efficiency: "optimise algorithms; reduce overhead"
reliability: "increase retries; improve test mocks"
resilience: "add fallbacks; improve monitoring"
maintainability: "refactor for clarity; improve documentation"
security: "harden authentication; add input validation"
latency: "optimise I/O; use caching"
energy: "batch work; reduce polling"
alignment_violation: "review alignment policies; add safeguards"
