scraper_bot:
  weights:
    profitability: 0.36
    efficiency: 0.36
    reliability: 0.14
    resilience: 0.14
    maintainability: 0.07
    security: 0.21
    latency: -0.21
    energy: -0.07
  veto:
    security: {min: 0.5}
    alignment_violation: {equals: true}

content_generator:
  weights:
    profitability: 0.40
    efficiency: 0.27
    reliability: 0.20
    resilience: 0.07
    maintainability: 0.13
    security: 0.13
    latency: -0.13
    energy: -0.07
  veto:
    security: {min: 0.45}
    alignment_violation: {equals: true}

growth_planner:
  weights:
    profitability: 0.438
    efficiency: 0.188
    reliability: 0.125
    resilience: 0.125
    maintainability: 0.125
    security: 0.125
    latency: -0.063
    energy: -0.063
  veto:
    security: {min: 0.6}
    alignment_violation: {equals: true}
