scraper_bot:
  weights:
    profitability: 0.230769
    efficiency: 0.230769
    reliability: 0.089744
    resilience: 0.089744
    maintainability: 0.044872
    security: 0.134615
    latency: -0.134615
    energy: -0.044872
  veto:
    security: {min: 0.5}
    alignment_violation: {equals: true}

content_generator:
  weights:
    profitability: 0.285714
    efficiency: 0.192857
    reliability: 0.142857
    resilience: 0.05
    maintainability: 0.092857
    security: 0.092857
    latency: -0.092857
    energy: -0.05
  veto:
    security: {min: 0.45}
    alignment_violation: {equals: true}

growth_planner:
  weights:
    profitability: 0.34984
    efficiency: 0.15016
    reliability: 0.09984
    resilience: 0.09984
    maintainability: 0.09984
    security: 0.09984
    latency: -0.050319
    energy: -0.050319
  veto:
    security: {min: 0.6}
    alignment_violation: {equals: true}
