name: Tests

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup_env.sh'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup_env.sh'
      - '.github/workflows/tests.yml'
  workflow_dispatch:
    inputs:
      stress:
        description: 'Run stress tests'
        required: false
        default: 'false'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: bash ./setup_env.sh
      - name: Check for ungoverned embedding calls
        run: python scripts/check_governed_embeddings.py
      - name: Run unit and integration tests
        run: pytest -k "not fuzz"
      - name: Run fuzz and property-based tests
        run: pytest tests/fuzz tests/test_bot_testing_bot_property.py tests/test_communication_testing_bot_property.py

  stress-tests:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.stress == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: bash ./setup_env.sh
      - name: Run stress tests
        run: RUN_STRESS_TESTS=1 pytest tests/stress
