name: Tests

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup_env.sh'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'
      - 'setup_env.sh'
      - '.github/workflows/tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: bash ./setup_env.sh
      - name: Run tests
        run: pytest
